import { UserProvider } from "@/components/StateMange/MyContext";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";
import GenaralChat from "@/components/GenaralChat";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <SignedOut>
            <SignInButton />
          </SignedOut>
          <SignedIn>
            <Navbar />
            <GenaralChat />
          </SignedIn> */}
        <UserProvider>
          <Toaster />
          <Navbar />
          {children}
          <GenaralChat />
        </UserProvider>
      </body>
    </html>
  );
}
