import Navbar from "@/components/Navbar";
import { UserProvider } from "@/components/StateMange/MyContext";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import { SocketProvider } from "@/components/StateMange/SocketProvider";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <SignedOut>
            <SignInButton />
          </SignedOut>
          <SignedIn>
            <Navbar />
            <GenaralChat />
          </SignedIn> */}
        <UserProvider>
          <SocketProvider>
            <Toaster />
            <Navbar />
            {children}
          </SocketProvider>
        </UserProvider>
      </body>
    </html>
  );
}
